### ISSUE TITLE
Build fails with 'rename: unsatisified constraints (Directory not empty)'

### ISSUE THREAD

**Issue by francisdb** [choucrifahed/sbt-elm#2]
Ubuntu Linux Xenial 16.04
running build on Jenkins CI with latest elm installed through `sudo npm install -g elm`

java.lang.RuntimeException: Failed to parse `elm` output. This is the original `elm` output:
Starting downloads...

```
...
elm-make: elm-lang-websocket-e009e6c: rename: unsatisified constraints (Directory not empty)
    at sbt.elm.SbtElm$PscOutputParser$.readProblems(SbtElm.scala:205)
    at sbt.elm.SbtElm$.doCompile(SbtElm.scala:179)
    at sbt.elm.SbtElm$$anonfun$6$$anonfun$8.apply(SbtElm.scala:127)
    at sbt.elm.SbtElm$$anonfun$6$$anonfun$8.apply(SbtElm.scala:119)
    at com.typesafe.sbt.web.incremental.package$.syncIncremental(package.scala:228)
    at sbt.elm.SbtElm$$anonfun$6.apply(SbtElm.scala:119)
    at sbt.elm.SbtElm$$anonfun$6.apply(SbtElm.scala:110)
    at scala.Function1$$anonfun$compose$1.apply(Function1.scala:47)
    at sbt.$tilde$greater$$anonfun$$u2219$1.apply(TypeFunctions.scala:40)
    at sbt.std.Transform$$anon$4.work(System.scala:63)
    at sbt.Execute$$anonfun$submit$1$$anonfun$apply$1.apply(Execute.scala:228)
    at sbt.Execute$$anonfun$submit$1$$anonfun$apply$1.apply(Execute.scala:228)
    at sbt.ErrorHandling$.wideConvert(ErrorHandling.scala:17)
    at sbt.Execute.work(Execute.scala:237)
    at sbt.Execute$$anonfun$submit$1.apply(Execute.scala:228)
    at sbt.Execute$$anonfun$submit$1.apply(Execute.scala:228)
    at sbt.ConcurrentRestrictions$$anon$4$$anonfun$1.apply(ConcurrentRestrictions.scala:159)
    at sbt.CompletionService$$anon$2.call(CompletionService.scala:28)
    at java.util.concurrent.FutureTask.run(FutureTask.java:266)
    at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
    at java.util.concurrent.FutureTask.run(FutureTask.java:266)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
    at java.lang.Thread.run(Thread.java:745)
[error] (root/web-assets-test:elmMake) Failed to parse `elm` output. This is the original `elm` output:
[error] Starting downloads...
[error] 
[error] elm-make: elm-lang-websocket-e009e6c: rename: unsatisified constraints (Directory not empty)
```

**Comment by francisdb** [comment]
Seeing the same on my mac when running: 

```
rm -rf elm-stuff
sbt clean test
```

doing a `elm-package install -y` before calling sbt seems to help

**Comment by francisdb** [comment]
This ticket mentions something about ELM_HOME not being set
https://github.com/evancz/elm-architecture-tutorial/issues/13

And this one about two modules sharing the elm-stuff folder
https://github.com/evancz/elm-architecture-tutorial/issues/32

I do have a multimodule sbt build with 2 play modules

**Comment by francisdb** [comment]
I was able to fix this by adding `.disablePlugins(SbtElm)` to the second module. I guess it would be ok to just mention in the README that this plugin can only be active on one module in a multimodule sbt project.
